# Generated by Django 4.2.11 on 2026-06-16 01:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import weir.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='鱼梁唯一编号，不能重复', max_length=50, unique=True, verbose_name='鱼梁编号')),
                ('name', models.CharField(max_length=100, verbose_name='鱼梁名称')),
                ('location', models.CharField(max_length=200, verbose_name='所在位置')),
                ('build_year', models.IntegerField(blank=True, null=True, validators=[weir.validators.validate_year], verbose_name='建造年代')),
                ('gate_count', models.IntegerField(default=1, validators=[weir.validators.validate_non_negative], verbose_name='闸口数量')),
                ('structure_desc', models.TextField(blank=True, verbose_name='结构描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '鱼梁档案',
                'verbose_name_plural': '鱼梁档案',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('fish_species', models.CharField(max_length=50, verbose_name='鱼种')),
                ('weight', models.FloatField(help_text='捕获重量，不能为负数', validators=[weir.validators.validate_non_negative], verbose_name='重量(公斤)')),
                ('quantity', models.IntegerField(default=0, help_text='捕获数量，不能为负数', validators=[weir.validators.validate_non_negative], verbose_name='数量')),
                ('recorder', models.CharField(blank=True, max_length=50, verbose_name='记录人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('weir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_records', to='weir.weir', verbose_name='所属鱼梁')),
            ],
            options={
                'verbose_name': '收获记录',
                'verbose_name_plural': '收获记录',
                'ordering': ['-record_date', 'weir__code'],
            },
        ),
        migrations.CreateModel(
            name='HarvestEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_date', models.DateField(verbose_name='估算日期')),
                ('estimated_weight', models.FloatField(default=0, validators=[weir.validators.validate_non_negative], verbose_name='估算重量(公斤)')),
                ('gate_strategy', models.CharField(blank=True, max_length=200, verbose_name='闸口策略组合')),
                ('water_level', models.FloatField(blank=True, null=True, verbose_name='当日水位')),
                ('has_water_data', models.BooleanField(default=False, verbose_name='是否有水位数据')),
                ('actual_weight', models.FloatField(default=0, validators=[weir.validators.validate_non_negative], verbose_name='实际重量(公斤)')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='估算准确率(%)')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='计算时间')),
                ('weir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_estimates', to='weir.weir', verbose_name='所属鱼梁')),
            ],
            options={
                'verbose_name': '收获估算',
                'verbose_name_plural': '收获估算',
                'ordering': ['-estimate_date', 'weir__code'],
            },
        ),
        migrations.CreateModel(
            name='GateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_number', models.CharField(max_length=20, verbose_name='闸口编号')),
                ('status', models.CharField(choices=[('open', '开启'), ('closed', '关闭')], max_length=10, verbose_name='状态')),
                ('change_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='变更时间')),
                ('reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('weir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_statuses', to='weir.weir', verbose_name='所属鱼梁')),
            ],
            options={
                'verbose_name': '闸口状态',
                'verbose_name_plural': '闸口状态',
                'ordering': ['-change_time', 'weir__code', 'gate_number'],
            },
        ),
        migrations.CreateModel(
            name='FishSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('observe_time', models.TimeField(verbose_name='观测时间')),
                ('fish_type', models.CharField(max_length=50, verbose_name='鱼群种类')),
                ('estimated_count', models.IntegerField(validators=[weir.validators.validate_non_negative], verbose_name='预估数量')),
                ('direction', models.CharField(choices=[('upstream', '逆流而上'), ('downstream', '顺流而下')], max_length=20, verbose_name='游动方向')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('weir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_schools', to='weir.weir', verbose_name='所属鱼梁')),
            ],
            options={
                'verbose_name': '鱼群记录',
                'verbose_name_plural': '鱼群记录',
                'ordering': ['-record_date', '-observe_time', 'weir__code'],
            },
        ),
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('water_level', models.FloatField(help_text='水位高度，不能为负数', validators=[weir.validators.validate_non_negative], verbose_name='水位(米)')),
                ('flow_rate', models.FloatField(help_text='水流速度，不能为负数', validators=[weir.validators.validate_non_negative], verbose_name='流速(m/s)')),
                ('weather', models.CharField(choices=[('晴', '晴'), ('多云', '多云'), ('阴', '阴'), ('小雨', '小雨'), ('中雨', '中雨'), ('大雨', '大雨'), ('暴雨', '暴雨'), ('雪', '雪'), ('雾', '雾')], max_length=20, verbose_name='天气状况')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_primary', models.BooleanField(default=True, help_text='同一鱼梁同一天只能有一条主记录', verbose_name='是否主记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('weir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_levels', to='weir.weir', verbose_name='所属鱼梁')),
            ],
            options={
                'verbose_name': '水位记录',
                'verbose_name_plural': '水位记录',
                'ordering': ['-record_date', 'weir__code'],
                'indexes': [models.Index(fields=['weir', 'record_date'], name='weir_waterl_weir_id_49e05b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='waterlevel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('weir', 'record_date', 'is_primary'), name='unique_primary_water_level_per_day'),
        ),
        migrations.AddIndex(
            model_name='harvestrecord',
            index=models.Index(fields=['weir', 'record_date'], name='weir_harves_weir_id_d24834_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestestimate',
            index=models.Index(fields=['weir', 'estimate_date'], name='weir_harves_weir_id_14cfdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='harvestestimate',
            constraint=models.UniqueConstraint(fields=('weir', 'estimate_date'), name='unique_estimate_per_day'),
        ),
        migrations.AddIndex(
            model_name='gatestatus',
            index=models.Index(fields=['weir', 'change_time'], name='weir_gatest_weir_id_0f98d5_idx'),
        ),
    ]
